### ISSUE TITLE
Partitioning train, validation e test

### ISSUE THREAD

**Issue by Tezze2001** [Tezze2001/brain-tumor-analysis#7]
Suddivisione del dataset dato con relativo studio della suddivisione e salvataggio dei dati. In questo modo è possibile definire e ed eseguire tutti i 3 modelli sulla stessa partizione

**Comment by TommasoFerrario18** [comment]
Divisione di Train (80%) e Test (20%) considerando la struttura del dataset

**Comment by Tezze2001** [comment]
TO DO: partitioning PCA dataset trasfromed
